project:
  type: website

website:
  title: "Experimenting with LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/julialevine7
        
format:
  html:
    theme: vapor
    css: styles.css

execute:
  freeze: auto


